Add-Type -AssemblyName System.Drawing
$bitmap = [System.Drawing.Bitmap]::new(256,256)
$graphics = [System.Drawing.Graphics]::FromImage($bitmap)
$graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
$graphics.Clear([System.Drawing.Color]::FromArgb(16,18,24))
$planet = [System.Drawing.SolidBrush]::new([System.Drawing.ColorTranslator]::FromHtml('#c96442'))
$orbit = [System.Drawing.Pen]::new([System.Drawing.ColorTranslator]::FromHtml('#f2f0ec'),10)
$moon = [System.Drawing.SolidBrush]::new([System.Drawing.ColorTranslator]::FromHtml('#48d8c8'))
$graphics.FillEllipse($planet,57,57,142,142)
$graphics.TranslateTransform(128,128)
$graphics.RotateTransform(-28)
$graphics.DrawEllipse($orbit,-109,-41,218,82)
$graphics.ResetTransform()
$graphics.FillEllipse($moon,188,40,28,28)
$bitmap.Save((Join-Path $PSScriptRoot 'icon.png'),[System.Drawing.Imaging.ImageFormat]::Png)
$icon = [System.Drawing.Icon]::FromHandle($bitmap.GetHicon())
$stream = [System.IO.File]::Create((Join-Path $PSScriptRoot 'icon.ico'))
$icon.Save($stream)
$stream.Dispose()
$icon.Dispose()
$moon.Dispose()
$orbit.Dispose()
$planet.Dispose()
$graphics.Dispose()
$bitmap.Dispose()
